### ISSUE TITLE
handleAuthStart doesn't resolve on live app on first install

### ISSUE THREAD

**Issue by PaulvdDool** [ctrlaltdylan/shopify-nextjs-toolbox#13]
Version: "shopify-nextjs-toolbox": "^0.2.0-beta.1"

I'm having issues with the OAuth flow on my live app.

When a merchant clicks 'Install app' on my listing page, the first time the `api/auth` path doesn't resolve (keeps PENDING in the DevTools). The merchant is then redirected to the following URL:
[https://]shop-slug.myshopify.com/apps/unique-app-id/?hmac=hmac-string&shop=shop-slug.myshopify.com&timestamp=1234567

If the merchant would return to the listing page and click 'Install app' again, it does work.
They're then redirected to the OAuth URL:
[https://]shop-slug.myshopify.com/admin/oauth/authorize?client_id=api-key&scope=scopes&redirect_uri=redirect-uri&state=nonce.

After they grant access for my app, they're again redirected to:
[https://]shop-slug.myshopify.com/admin/apps/unique-app-id/?hmac=hmac-string&shop=shop-slug.myshopify.com&timestamp=1234567

Notice how this URL looks almost exactly the same as the wrong redirect I mention above, but now it correctly adds the `admin/` part of the route between the shop name and `/apps/...`.

I'm using your package and I took pointers from the example repo you have linked.
- https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs

That means that I have a `pages/index.tsx` file where a POST is being done the the `api/auth` endpoint.

```
import React, { useEffect } from "react";
import qs from "querystring";
import axios from 'axios';
import { Spinner } from "@shopify/polaris";

export default function Home() {
  // page context params
  useEffect( () => {
    if ( typeof window !== "undefined" && window.location ) {
      const query = qs.parse(window.location.search);
      axios
        .post("/api/auth", {
          query: query,
        })
        .then( ( response: any ) => {
          console.info( 'Endpoint resolved' );
          if ( response.data.redirectTo ) {
            if (window.parent) {
              window.parent.location.href = response.data.redirectTo;
            } else {
              window.location.href = response.data.redirectTo;
            }
          }
        })
        .catch( function (error) {
          // handle error
          console.error( error);
        } );
    }
  }, [] );

  return (
    <div className="spinner-centered">
      <Spinner size="large" />
      <p>Loading...</p>
    </div>
  );
}
```

API route `api/auth`
```
import { handleAuthStart } from 'shopify-nextjs-toolbox';

export default handleAuthStart;
```

I've copied the handleAuthStart function to a local file and tried using that to debug and it seems that it runs through the entire function, but it doesn't resolve.

I've added the issue to the Shopify Community forum as well.
https://community.shopify.com/c/shopify-apis-and-sdks/app-install-doesn-t-link-to-correct-oauth-url

And if you want to see the issue in action, you can try here:
https://apps.shopify.com/doppelganger-app

**Comment by ctrlaltdylan** [comment]
Please update to the newest v2 version of the app and try again, most likely you were using an old beta version that has a bug.
