### ISSUE TITLE
Donate to support development

### ISSUE THREAD

**Issue by tracy-codes** [ctrlaltdylan/shopify-nextjs-toolbox#8]
Hi! Just wanted to say, this package saved me at least 8 hours (if not more) with an auth rewrite after Shopify forced my team to move to cookie-less authentication.

If there's any way for my team to donate to help support the continued development of this package, please let me know!

**Comment by ctrlaltdylan** [comment]
Hi, sorry for the late reply. Life came at me quick with the Shopify apps I maintain & a new addition to our family.

Humbled you want to support my project and so happy to help me financially.

I need to do some research on how to best offer this, perhaps Patreon? I'm not sure. I'll add links to the README once I set it up.

**Comment by ctrlaltdylan** [comment]
If you would like to sponsor the development this project, as well as another I have coming please consider sponsoring me on Github Sponsors.

Here's the link: https://github.com/sponsors/ctrlaltdylan
